[build]
  publish = "dist/"

[[redirects]]
  from = "/director/*"
  to = "https://vidlium-director.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/preview"
  to = "https://vidlium-director-preview.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/preview/*"
  to = "https://vidlium-director-preview.netlify.app/:splat"
  status = 200